manifest:
  remotes:
    - name: wdtamagi
      url-base: https://github.com/wdtamagi
    - name: charlesmst
      url-base: https://github.com/charlesmst
  projects:
    - name: zmk
      remote: wdtamagi
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: charlesmst
      revision: main
  self:
    path: config
