manifest:
  remotes:
    - name: wdtamagi
      url-base: https://github.com/wdtamagi
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: wdtamagi
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: nice-view-gem
      remote: m165437
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
  self:
    path: config
