manifest:
  remotes:
    - name: wdtamagi
      url-base: https://github.com/wdtamagi
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: wdtamagi
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: nice-view-gem
      remote: wdtamagi
      revision: main
    - name: zmk-pmw3610-driver
      remote: wdtamagi
      revision: main
    - name: zmk-behavior-mouse-key-toggle
      remote: badjeff
      revision: main
    - name: zmk-output-behavior-listener
      remote: badjeff
      revision: main
    - name: zmk-input-processor-mixer
      remote: badjeff
      revision: main
    - name: zmk-input-processor-report-rate-limit
      remote: badjeff
      revision: main
    - name: zmk-input-processor-xyz
      remote: badjeff
      revision: main
  self:
    path: config
